version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - GATSBY_DEFAULT_SITE_URL=https://kcddenmark.dk
    volumes:
      - ./src:/app/src # Links the source files to the running container
    ports:
      - "3000:8000"
