name: Commit Stage
on:
  push:
    branches: ["staging"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cloud-native-nordics/kcddenmark.dk
  VERSION: ${{ github.sha }}

jobs:
  package:
    name: Package and Publish
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Set up Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.2.0
      - name: Install dependencies
        run: npm ci
      - name: Build SPA
        run: |
          npm run build
      - name: Configure NGINX
        run: |
          cp nginx/* public/
      - name: Package SPA
        run: |
          pack build ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            --builder paketobuildpacks/builder-jammy-base \
            --path public
      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
      - name: Publish container image (latest)
        run: |
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
